// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: api/proto/v1alpha1/generator.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationEngine_GetSchema_FullMethodName           = "/protocols.GenerationEngine/GetSchema"
	GenerationEngine_UpdateConfiguration_FullMethodName = "/protocols.GenerationEngine/UpdateConfiguration"
	GenerationEngine_Generate_FullMethodName            = "/protocols.GenerationEngine/Generate"
)

// GenerationEngineClient is the client API for GenerationEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenerationEngineClient interface {
	GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	UpdateConfiguration(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type generationEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationEngineClient(cc grpc.ClientConnInterface) GenerationEngineClient {
	return &generationEngineClient{cc}
}

func (c *generationEngineClient) GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, GenerationEngine_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generationEngineClient) UpdateConfiguration(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, GenerationEngine_UpdateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generationEngineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, GenerationEngine_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerationEngineServer is the server API for GenerationEngine service.
// All implementations must embed UnimplementedGenerationEngineServer
// for forward compatibility.
type GenerationEngineServer interface {
	GetSchema(context.Context, *Empty) (*GetSchemaResponse, error)
	UpdateConfiguration(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedGenerationEngineServer()
}

// UnimplementedGenerationEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationEngineServer struct{}

func (UnimplementedGenerationEngineServer) GetSchema(context.Context, *Empty) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedGenerationEngineServer) UpdateConfiguration(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (UnimplementedGenerationEngineServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedGenerationEngineServer) mustEmbedUnimplementedGenerationEngineServer() {}
func (UnimplementedGenerationEngineServer) testEmbeddedByValue()                          {}

// UnsafeGenerationEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationEngineServer will
// result in compilation errors.
type UnsafeGenerationEngineServer interface {
	mustEmbedUnimplementedGenerationEngineServer()
}

func RegisterGenerationEngineServer(s grpc.ServiceRegistrar, srv GenerationEngineServer) {
	// If the following call pancis, it indicates UnimplementedGenerationEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationEngine_ServiceDesc, srv)
}

func _GenerationEngine_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationEngineServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationEngine_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationEngineServer).GetSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenerationEngine_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationEngineServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationEngine_UpdateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationEngineServer).UpdateConfiguration(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenerationEngine_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationEngineServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationEngine_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationEngineServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerationEngine_ServiceDesc is the grpc.ServiceDesc for GenerationEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocols.GenerationEngine",
	HandlerType: (*GenerationEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _GenerationEngine_GetSchema_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _GenerationEngine_UpdateConfiguration_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _GenerationEngine_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1alpha1/generator.proto",
}
