// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: api/proto/v1alpha1/remediator.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemediationEngine_GetSchema_FullMethodName           = "/protocols.RemediationEngine/GetSchema"
	RemediationEngine_UpdateConfiguration_FullMethodName = "/protocols.RemediationEngine/UpdateConfiguration"
	RemediationEngine_Generate_FullMethodName            = "/protocols.RemediationEngine/Generate"
	RemediationEngine_Remediate_FullMethodName           = "/protocols.RemediationEngine/Remediate"
)

// RemediationEngineClient is the client API for RemediationEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemediationEngineClient interface {
	GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	UpdateConfiguration(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	Remediate(ctx context.Context, in *RemediationRequest, opts ...grpc.CallOption) (*RemediationResponse, error)
}

type remediationEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRemediationEngineClient(cc grpc.ClientConnInterface) RemediationEngineClient {
	return &remediationEngineClient{cc}
}

func (c *remediationEngineClient) GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, RemediationEngine_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationEngineClient) UpdateConfiguration(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, RemediationEngine_UpdateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationEngineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, RemediationEngine_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationEngineClient) Remediate(ctx context.Context, in *RemediationRequest, opts ...grpc.CallOption) (*RemediationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemediationResponse)
	err := c.cc.Invoke(ctx, RemediationEngine_Remediate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemediationEngineServer is the server API for RemediationEngine service.
// All implementations must embed UnimplementedRemediationEngineServer
// for forward compatibility.
type RemediationEngineServer interface {
	GetSchema(context.Context, *Empty) (*GetSchemaResponse, error)
	UpdateConfiguration(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	Remediate(context.Context, *RemediationRequest) (*RemediationResponse, error)
	mustEmbedUnimplementedRemediationEngineServer()
}

// UnimplementedRemediationEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemediationEngineServer struct{}

func (UnimplementedRemediationEngineServer) GetSchema(context.Context, *Empty) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedRemediationEngineServer) UpdateConfiguration(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (UnimplementedRemediationEngineServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedRemediationEngineServer) Remediate(context.Context, *RemediationRequest) (*RemediationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remediate not implemented")
}
func (UnimplementedRemediationEngineServer) mustEmbedUnimplementedRemediationEngineServer() {}
func (UnimplementedRemediationEngineServer) testEmbeddedByValue()                           {}

// UnsafeRemediationEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemediationEngineServer will
// result in compilation errors.
type UnsafeRemediationEngineServer interface {
	mustEmbedUnimplementedRemediationEngineServer()
}

func RegisterRemediationEngineServer(s grpc.ServiceRegistrar, srv RemediationEngineServer) {
	// If the following call pancis, it indicates UnimplementedRemediationEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemediationEngine_ServiceDesc, srv)
}

func _RemediationEngine_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationEngineServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationEngine_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationEngineServer).GetSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationEngine_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationEngineServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationEngine_UpdateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationEngineServer).UpdateConfiguration(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationEngine_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationEngineServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationEngine_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationEngineServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationEngine_Remediate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemediationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationEngineServer).Remediate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationEngine_Remediate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationEngineServer).Remediate(ctx, req.(*RemediationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemediationEngine_ServiceDesc is the grpc.ServiceDesc for RemediationEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemediationEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocols.RemediationEngine",
	HandlerType: (*RemediationEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _RemediationEngine_GetSchema_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _RemediationEngine_UpdateConfiguration_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _RemediationEngine_Generate_Handler,
		},
		{
			MethodName: "Remediate",
			Handler:    _RemediationEngine_Remediate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1alpha1/remediator.proto",
}
